version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: pftp/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pftp-frontend.rule=Host(`pftp.redcouch.at`)"
      - "traefik.http.routers.pftp-frontend.entrypoints=websecure"
      - "traefik.http.routers.pftp-frontend.tls.certresolver=myresolver"
    networks:
      internal:
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: pftp/backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pftp-backend.rule=Host(`pftp.backend.redcouch.at`)"
      - "traefik.http.routers.pftp-backend.entrypoints=websecure"
      - "traefik.http.routers.pftp-backend.tls.certresolver=myresolver"
    networks:
      internal:
    restart: always
networks:
  internal:
    external:
      name: paddy_internal