# define nodejs baseimage
FROM node:20.17.0-alpine

# expose ports
EXPOSE 4200

# set target image directory
WORKDIR /opt/frontend

# add all files to image directory
ADD . /opt/frontend

# install dependencies
RUN npm install

# compile
# ARG SOCKET_URL
RUN cd ./applications/common && npm run build

# set target image directory
WORKDIR /opt/frontend/applications/frontend

# start
ENTRYPOINT npm run start