# define nodejs baseimage
FROM node:18.15.0-alpine

# expose ports
EXPOSE 5200

# set target image directory
WORKDIR /opt/backend

# add all files to image directory
ADD . /opt/backend

# install dependencies
RUN npm install

# compile
RUN cd ./applications/common && npm run build
RUN cd ./applications/backend && npm run build

# set target image directory
WORKDIR /opt/backend/applications/backend

# start
ENTRYPOINT npm run start