version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    image: charityroyale/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.charityroyale-frontend.rule=Host(`charityroyale.redcouch.at`)"
      - "traefik.http.routers.charityroyale-frontend.entrypoints=websecure"
      - "traefik.http.routers.charityroyale-frontend.tls.certresolver=myresolver"
    networks:
      internal:
    restart: always

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    image: charityroyale/backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.charityroyale-backend.rule=Host(`charityroyale.backend.redcouch.at`)"
      - "traefik.http.routers.charityroyale-backend.entrypoints=websecure"
      - "traefik.http.routers.charityroyale-backend.tls.certresolver=myresolver"
    networks:
      internal:
    restart: always
networks:
  internal:
    external:
      name: paddy_internal